# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUEUED', 'QUEUED'), ('STARTED', 'STARTED'), ('IN-PROGRESS', 'IN-PROGRESS'), ('COMPLETE', 'COMPLETE'), ('TIE', 'TIE'), ('CANCELLED', 'CANCELLED')], default='QUEUED', max_length=20)),
                ('game_type', models.CharField(choices=[('LEAGUE', 'LEAGUE'), ('QUARTER_FINAL', 'QUARTER FINAL'), ('SEMI_FINAL', 'SEMI FINAL'), ('FINAL', 'FINAL')], default='LEAGUE', max_length=20)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to=settings.AUTH_USER_MODEL)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
